#!/usr/bin/env node

/**
 * Amori API - Environment Setup Script
 * Generates a .env file with required environment variables
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const ENV_FILE = path.join(__dirname, "..", ".env");
const ENV_EXAMPLE = path.join(__dirname, "..", ".env.example");

const envTemplate = `# Amori API Environment Variables
# Generated by setup-env.js

# Server Configuration
PORT=3000
NODE_ENV=development

# Database (PostgreSQL)
DATABASE_URL=postgresql://amori:secret@localhost:5432/amori

# Redis
REDIS_URL=redis://localhost:6379

# Supabase
SUPABASE_URL=
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# OpenAI
OPENAI_API_KEY=

# Email (Optional)
# RESEND_API_KEY=
`;

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log("\n🩷 Amori API - Environment Setup\n");

  // Check if .env already exists
  if (fs.existsSync(ENV_FILE)) {
    const overwrite = await question(".env file already exists. Overwrite? (y/N): ");
    if (overwrite.toLowerCase() !== "y") {
      console.log("Setup cancelled.");
      rl.close();
      return;
    }
  }

  console.log("\nPlease provide the following configuration values.");
  console.log("Press Enter to use default values shown in brackets.\n");

  // Collect values
  const port = (await question("PORT [3000]: ")) || "3000";
  const nodeEnv = (await question("NODE_ENV [development]: ")) || "development";
  const databaseUrl =
    (await question("DATABASE_URL [postgresql://amori:secret@localhost:5432/amori]: ")) ||
    "postgresql://amori:secret@localhost:5432/amori";
  const redisUrl = (await question("REDIS_URL [redis://localhost:6379]: ")) || "redis://localhost:6379";

  console.log("\n--- Supabase Configuration ---");
  const supabaseUrl = await question("SUPABASE_URL: ");
  const supabaseAnonKey = await question("SUPABASE_ANON_KEY: ");
  const supabaseServiceKey = await question("SUPABASE_SERVICE_ROLE_KEY: ");

  console.log("\n--- OpenAI Configuration ---");
  const openaiKey = await question("OPENAI_API_KEY: ");

  console.log("\n--- Optional Services ---");
  const resendKey = await question("RESEND_API_KEY (press Enter to skip): ");

  // Build env content
  let envContent = `# Amori API Environment Variables
# Generated by setup-env.js on ${new Date().toISOString()}

# Server Configuration
PORT=${port}
NODE_ENV=${nodeEnv}

# Database (PostgreSQL)
DATABASE_URL=${databaseUrl}

# Redis
REDIS_URL=${redisUrl}

# Supabase
SUPABASE_URL=${supabaseUrl}
SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}

# OpenAI
OPENAI_API_KEY=${openaiKey}
`;

  if (resendKey) {
    envContent += `
# Email
RESEND_API_KEY=${resendKey}
`;
  }

  // Write .env file
  fs.writeFileSync(ENV_FILE, envContent);
  console.log(`\n✅ Created ${ENV_FILE}`);

  // Also create .env.example if it doesn't exist
  if (!fs.existsSync(ENV_EXAMPLE)) {
    fs.writeFileSync(ENV_EXAMPLE, envTemplate);
    console.log(`✅ Created ${ENV_EXAMPLE}`);
  }

  console.log("\n🚀 Setup complete! You can now run:");
  console.log("   docker-compose up -d   # Start PostgreSQL and Redis");
  console.log("   bun run dev            # Start the development server\n");

  rl.close();
}

main().catch((err) => {
  console.error("Setup failed:", err);
  rl.close();
  process.exit(1);
});
